### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by dschinkel** [albinotonnina/react-truncate-string#7]
it's not truncating anything

`<TruncateString text="abdctafdafdsfsdddd" truncateAt={10} />`

nothing happens.  It renders the full string.

**Comment by albinotonnina** [comment]
You're trying to truncate a word. There are no spaces in there. This library truncate strings, meaning text with spaces. 
Please read the Readme.

**Comment by dschinkel** [comment]
eh, ok thanks.

**Comment by albinotonnina** [comment]
I realized the last sentence sounded snarky. Apologies.
I guess I was trying to echo your "Is not working".
Like you said, there is an **edge case** that I don't cover with this library. 
Therefore the library **works**.

To be honest I don't think that dealing with the truncation of **strings without spaces** would be that interesting.
It would be if the truncation would follow grammar rules, but then it would need to first deduce the language, then apply the specific rules (each language may have different rules for truncation). You see we wouldn't be talking anymore about a 1kb library.

This library, let me attempt a better definition, has the purpose to truncate **sentences**. 
Do you have examples of other libraries that perform the truncation the way you expect it?

If you think this feature could be useful and want to contribute, feel free to open a PR and I'll review it.

**Comment by albinotonnina** [comment]
@dschinkel I updated the README. I make clear that spaces are required for the truncation to happen.
Thank you for pointing that out.

**Comment by dschinkel** [comment]
>To be honest I don't think that dealing with the truncation of strings without spaces would be that interesting

I was using it to try and truncate full names of people on my site.  I had to squeeze people into a grid so being able to truncate would be useful.

I would contribute but I'm really focused on getting some new stuff out for the site.
